// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBezwshjwjYhA1NSCushU7I8SJx0KowarY',
    appId: '1:950396555093:android:85f81cf3a68b778102e9dc',
    messagingSenderId: '950396555093',
    projectId: 'freshkart-6c7df',
    storageBucket: 'freshkart-6c7df.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqwkuAW_Ygceio5n9TY1F93FhGyRpRYUg',
    appId: '1:950396555093:web:947f53e4bc75a9e402e9dc',
    messagingSenderId: '950396555093',
    projectId: 'freshkart-6c7df',
    authDomain: 'freshkart-6c7df.firebaseapp.com',
    storageBucket: 'freshkart-6c7df.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIK7oT2DEiOcI6pHYhVjE8d9Bcbhc_uTY',
    appId: '1:950396555093:ios:12d96ff7d010e02e02e9dc',
    messagingSenderId: '950396555093',
    projectId: 'freshkart-6c7df',
    storageBucket: 'freshkart-6c7df.firebasestorage.app',
    androidClientId: '950396555093-9d2pb1tlquqml8id27bnmadjo4o2aita.apps.googleusercontent.com',
    iosClientId: '950396555093-q1ff9copalufcsa05vlb32beaa4sgd82.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyFresh',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIK7oT2DEiOcI6pHYhVjE8d9Bcbhc_uTY',
    appId: '1:950396555093:ios:12d96ff7d010e02e02e9dc',
    messagingSenderId: '950396555093',
    projectId: 'freshkart-6c7df',
    storageBucket: 'freshkart-6c7df.firebasestorage.app',
    androidClientId: '950396555093-9d2pb1tlquqml8id27bnmadjo4o2aita.apps.googleusercontent.com',
    iosClientId: '950396555093-q1ff9copalufcsa05vlb32beaa4sgd82.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyFresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqwkuAW_Ygceio5n9TY1F93FhGyRpRYUg',
    appId: '1:950396555093:web:d2d2d27685fb02f402e9dc',
    messagingSenderId: '950396555093',
    projectId: 'freshkart-6c7df',
    authDomain: 'freshkart-6c7df.firebaseapp.com',
    storageBucket: 'freshkart-6c7df.firebasestorage.app',
  );

}